version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: base_mairie
      MYSQL_USER: root
      MYSQL_PASSWORD: supersaiyan
      MYSQL_ROOT_PASSWORD: supersaiyan
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  backend:
    build:
      context: ../back-end
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mysql_db
    environment:
      - DB_NAME=base_mairie
      - DB_USER=root
      - DB_PASSWORD=supersaiyan
      - DB_HOST=mysql_db
    ports:
      - "5000:5000"
    networks:
      - mynetwork

  frontend:
    build:
      context: ../front-end
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork: