services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - ./config/mysql.env
    ports:
      - "3307:3306" # Port exposé pour l'hôte (3307), interne (3306)
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ../back-end  # ✅ Doit pointer vers `back-end/`
      dockerfile: Dockerfile  # ✅ Le Dockerfile doit être dans `back-end/`
    container_name: backend
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
      - ./config/backend.env
    ports:
      - "5001:5000"
    networks:
      - mynetwork
    volumes:
      - ./back-end:/app
      - /app/node_modules  # ✅ Éviter les conflits des dépendances


  frontend:
    build:
      context: ../front-end
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./config/frontend.env
    ports:
      - "3001:3000" # Port exposé pour le frontend
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork: