version: '3.8'

services:  
  # ----------------------------------  
  # 1. Service MySQL  
  # ----------------------------------  
  mysql_db:  
    image: mysql:8.0  
    container_name: mysql_db  
    env_file:  
      - ./config/mysql.env  
    ports:
      - "3307:3306"
    networks:  
      - mynetwork  
    healthcheck:  
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  
      interval: 10s  
      timeout: 5s  
      retries: 5  
      start_period: 30s  
    volumes:
      - mysql_data:/var/lib/mysql

  # ----------------------------------  
  # 2. Service Back-end (Node/Sequelize)  
  # ----------------------------------  
  backend:  
    container_name: backend  
    build:  
      context: ../back-end  
      dockerfile: Dockerfile  
    depends_on:  
      mysql_db:  
        condition: service_healthy  
    env_file:  
      - ./config/backend.env  
    networks:  
      - mynetwork  
    ports:  
      - "5001:5000"  
    volumes:  
      - ../back-end:/app  
      - /app/node_modules  
    command: npm start  
    restart: unless-stopped  

  # ----------------------------------  
  # 3. Service Front-end (React)  
  # ----------------------------------  
  frontend:  
    container_name: frontend  
    build:  
      context: ../front-end  
      dockerfile: Dockerfile  
    depends_on:  
      - backend  
    env_file:  
      - ./config/frontend.env  
    networks:  
      - mynetwork  
    ports:  
      - "3001:80"  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped  

# ----------------------------------  
# Réseau Docker partagé : mynetwork  
# ----------------------------------  
networks:  
  mynetwork:

# ----------------------------------  
# Volumes persistants  
# ----------------------------------  
volumes:
  mysql_data: