services:
  mysql_db:
    image: mysql:8.0
    env_file:
      - ./config/mysql.env
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ../back-end
      dockerfile: ../docker/Dockerfile.backend
    depends_on:
      mysql_db:
        condition: service_healthy
    env_file:
      - ./config/backend.env
    ports:
      - "5001:5000"
    networks:
      - mynetwork

  frontend:
    build:
      context: ../front-end
      dockerfile: ../docker/Dockerfile.frontend
    env_file:
      - ./config/frontend.env
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork: