services:
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: base_mairie
      MYSQL_ROOT_PASSWORD: supersaiyan
    ports:
      - "3307:3306"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ../back-end
      dockerfile: Dockerfile
    depends_on:
      mysql_db:
        condition: service_healthy
    environment:
      - DB_NAME=base_mairie
      - DB_USER=root
      - DB_PASSWORD=supersaiyan
      - DB_HOST=mysql_db
    ports:
      - "5001:5000"
    networks:
      - mynetwork

  frontend:
    build:
      context: ../front-end
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - mynetwork

networks:
  mynetwork: