# Utiliser Node.js 20
FROM node:20

# Définir le répertoire de travail
WORKDIR /app

# Copier uniquement le package.json et le package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install --legacy-peer-deps

# Copier les fichiers de l'application dans le conteneur
COPY . .

# Exposer le port 5000
EXPOSE 5001

# Commande pour démarrer l'application
CMD ["npm", "start"]